SELECT vw.TLN_ID,
       vw.TLN_DATETIME,
       vw.TLN_LOGDATE AS TLN_LOGDATE,
	   EXTRACT(YEAR FROM vw.TLN_DATETIME) AS TLN_YEAR,
	   CASE
    		WHEN EXTRACT(MONTH FROM vw.TLN_DATETIME) BETWEEN 1 AND 3 THEN 1
    		WHEN EXTRACT(MONTH FROM vw.TLN_DATETIME) BETWEEN 4 AND 6 THEN 2
    		WHEN EXTRACT(MONTH FROM vw.TLN_DATETIME) BETWEEN 7 AND 9 THEN 3
    		WHEN EXTRACT(MONTH FROM vw.TLN_DATETIME) BETWEEN 10 AND 12 THEN 4
  	   END AS TLN_QUARTER,
  	   EXTRACT(MONTH FROM vw.TLN_DATETIME) AS TLN_MONTH,
  	   EXTRACT(WEEK FROM vw.TLN_DATETIME) AS TLN_WEEK,
  	   EXTRACT(DAY FROM vw.TLN_DATETIME) AS TLN_DAY_NUM,
  	   CASE EXTRACT(weekday FROM vw.TLN_DATETIME)
    		WHEN 0 THEN 'Воскресенье'
            WHEN 1 THEN 'Понедельник'
            WHEN 2 THEN 'Вторник'
            WHEN 3 THEN 'Среда'
            WHEN 4 THEN 'Четверг'
            WHEN 5 THEN 'Пятница'
            WHEN 6 THEN 'Суббота'
  		END AS TLN_DAY,
  		CASE
           WHEN EXTRACT(weekday FROM vw.TLN_DATETIME) in (6,0) THEN 'Вых'
           ELSE 'Буд'
     	END AS TLN_DAYTYPE,
       EXTRACT(hour FROM vw.TLN_DATETIME) AS TLN_HOUR,
	   DATEADD(minute, vw.VER_DURATIONSCHEDULED/100, vw.TLN_DATETIME) AS TLN_DATETIME_END,
	   DATEADD(minute, -10, vw.TLN_DATETIME) AS TLN_DATETIME_BEG_EPG,
	   DATEADD(minute, 10, vw.TLN_DATETIME) AS TLN_DATETIME_END_EPG,
	   cm.MEDIAHILLS_ID AS CHANNEL_MEDIAHILLS_ID,
	   cm.EPG_ID AS CHANNEL_EPG_ID,
	   vw.TLN_OBJECTCLASS,vw.TLN_TIMEFRAMES,vw.TLN_CHA_ID,vw.TLN_SIS_ID,vw.TLN_MDV_ID_SOURCE,vw.TLN_ISPREMIERE_RIGHTS_CM,vw.TLN_ISPREMIERE_NONRIGHTS_CM,vw.TLN_ISRIGHTSPREMIERE_CM,vw.TLN_ISPREMIERE,vw.TLN_TIMELOCKED,vw.ASS_TITLE,vw.ASS_DURATIONSCHEDULED,vw.ASS_ACA_ID,vw.ASS_ID,vw.ASS_RAT_ID,vw.ASS_VCH_ID,vw.ASS_DIS_ID,vw.ASS_EPISODETITLE,vw.ASS_EPISODESLATE,vw.ASS_EPISODENUMBER,vw.ASS_EPISODESEASON,vw.ASS_PBSFD_ID,vw.ASS_COM_ID_SUPPLIER,vw.SER_TITLE,vw.SER_DURATIONSCHEDULED,vw.SER_ACA_ID,vw.SER_ID,vw.SER_RAT_ID,vw.SER_VCH_ID,vw.SER_DIS_ID,vw.VER_DESCRIPTION,vw.VER_VET_ID,vw.VER_PACKAGENUMBER,vw.VER_SLU_ID_PACKAGESTATUS,vw.VER_DURATIONSCHEDULED,vw.VER_SLU_ID_PBSMEDIASTATUS,vw.VER_RAT_ID,vw.VER_VCH_ID,vw.VER_ID,vw.VER_MFC_ID_AUDIOTYPE,vw.VER_ISSAP,vw.VER_ISCC,vw.VER_ISDVI,vw.VER_SLU_ID_ASPECTRATIO,vw.VER_SLU_ID_HIDEF,vw.VER_SLU_ID_EVENTTYPE,vw.VER_SLU_ID_RECORDTYPE,vw.VER_PBSUP_ID,vw.VER_ORIGSITE,vw.VER_ORIGPATH1,vw.VER_ORIGPATH2,vw.VER_ORIGPATH3,vw.VER_ORIGPATH4,vw.VER_DESTINATION,vw.VER_BACKUPPATH1,vw.VER_BACKUPPATH2,vw.VER_BACKUPPATH3,vw.VER_BACKUPPATH4,vw.VER_ISPOSTLOGOMATERIAL,vw.VER_CONTENTFLAG,vw.VER_ISSCREENINGCOMPLETE,vw.VER_PACKAGEHOUSE,vw.VER_TAPES,vw.VER_REVISIONNO,vw.VER_ISPBSDISTRIBUTORDIRECT,vw.VER_FEATURE,vw.VER_PUCC_ID,vw.VER_POAC_ID,vw.VER_PIWT_ID,vw.VER_PFS_ID,vw.VER_ISBILLABLE,vw.VER_PBSBT_ID,vw.VER_PBSBC_ID,vw.VER_PBSBS_ID,vw.VER_BILLTOCOMMENT,vw.VER_ISUCCIGNORED,vw.VER_UCCUPDATEUSERID,vw.VER_UCCUPDATEDATETIME,vw.VER_ISOACIGNORED,vw.VER_OACUPDATEUSERID,vw.VER_OACUPDATEDATETIME,vw.VER_ISIWTIGNORED,vw.VER_IWTUPDATEUSERID,vw.VER_IWTUPDATEDATETIME,vw.VER_MEF_ID_CC,vw.VER_ISSUBTITLE,vw.VER_LAN_ID_SUBTITLE,vw.PUCC_FORMSTATUS,vw.POAC_FORMSTATUS,vw.PIWT_FORMSTATUS,vw.PFS_FORMSTATUS,vw.TLN_DURATIONFRAMES,vw.TLN_ISARCHIVED,vw.TLN_UPDATEDATETIME,vw.TLN_UPDATEUSERID,vw.TLN_VET_ID,vw.TLN_TPT_ID,vw.TLN_PRF_ID,vw.TLN_ROT_ID,vw.TLN_OAS_ID,vw.TLN_CGTEXT,vw.TLN_PSB_ID,vw.TLN_SEGMENTTYPE,vw.TLNPBS_CONTACTS_PRODUCER,vw.TLNPBS_CONTACTS_PRODUCER_TEL,vw.TLNPBS_CONTACTS_TECH,vw.TLNPBS_CONTACTS_TECH_TEL,vw.TLNPBS_CONTACTS_NAME_1,vw.TLNPBS_CONTACTS_NAME_1_TEL,vw.TLNPBS_CONTACTS_NAME_2,vw.TLNPBS_CONTACTS_NAME_2_TEL,vw.TLNPBS_PBSUP_ID,vw.TLNPBS_ORIGPATH_ORIGSITE,vw.TLNPBS_ORIGPATH_PATH_1,vw.TLNPBS_ORIGPATH_PATH_2,vw.TLNPBS_ORIGPATH_PATH_3,vw.TLNPBS_ORIGPATH_PATH_4,vw.TLNPBS_ORIGPATH_PATH_DEST,vw.TLNPBS_BACKUP_PATH_1,vw.TLNPBS_BACKUP_PATH_2,vw.TLNPBS_BACKUP_PATH_3,vw.TLNPBS_BACKUP_PATH_4,vw.TLNPBS_ISPBSCOMMONCARRY,vw.TLNBLN_PBSBT_ID,vw.TLNBLN_PBSBC_ID,vw.TLNBLN_PBSBS_ID,vw.TLNBLN_BILLTOCOMMENT,vw.TLNBLN_SLU_ID_STATUS,vw.TLNBLN_ISBILLABLE,vw.TLNBLN_ISRECONREQUIRED,vw.NETWORKSOURCE,ISLOCALEVENT,vw.ISSTANDALONEEVENT,vw.ENDTIMEFRAMES

FROM VW_TIMELINE_PROGRAM vw
LEFT JOIN CHANNELS_MERGED cm ON cm.BV_ID = vw.TLN_CHA_ID
WHERE vw.TLN_OBJECTCLASS in ('PRO', 'RPO', 'EPS', 'EPR')
AND CAST(vw.TLN_DATETIME AS DATE) between ':start_date' and ':end_date'
